# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexis/Dev/aci-webapp-backend

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexis/Dev/aci-webapp-backend

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexis/Dev/aci-webapp-backend/CMakeFiles /home/alexis/Dev/aci-webapp-backend/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexis/Dev/aci-webapp-backend/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ACI

# Build rule for target.
ACI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ACI
.PHONY : ACI

# fast build rule for target.
ACI/fast:
	$(MAKE) -f CMakeFiles/ACI.dir/build.make CMakeFiles/ACI.dir/build
.PHONY : ACI/fast

#=============================================================================
# Target rules for targets named GrabCutExe

# Build rule for target.
GrabCutExe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GrabCutExe
.PHONY : GrabCutExe

# fast build rule for target.
GrabCutExe/fast:
	$(MAKE) -f CMakeFiles/GrabCutExe.dir/build.make CMakeFiles/GrabCutExe.dir/build
.PHONY : GrabCutExe/fast

#=============================================================================
# Target rules for targets named IdentityClassifier

# Build rule for target.
IdentityClassifier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IdentityClassifier
.PHONY : IdentityClassifier

# fast build rule for target.
IdentityClassifier/fast:
	$(MAKE) -f CMakeFiles/IdentityClassifier.dir/build.make CMakeFiles/IdentityClassifier.dir/build
.PHONY : IdentityClassifier/fast

#=============================================================================
# Target rules for targets named SpectralResidualSaliency

# Build rule for target.
SpectralResidualSaliency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpectralResidualSaliency
.PHONY : SpectralResidualSaliency

# fast build rule for target.
SpectralResidualSaliency/fast:
	$(MAKE) -f CMakeFiles/SpectralResidualSaliency.dir/build.make CMakeFiles/SpectralResidualSaliency.dir/build
.PHONY : SpectralResidualSaliency/fast

#=============================================================================
# Target rules for targets named SpectralResidualSaliencyExe

# Build rule for target.
SpectralResidualSaliencyExe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpectralResidualSaliencyExe
.PHONY : SpectralResidualSaliencyExe

# fast build rule for target.
SpectralResidualSaliencyExe/fast:
	$(MAKE) -f CMakeFiles/SpectralResidualSaliencyExe.dir/build.make CMakeFiles/SpectralResidualSaliencyExe.dir/build
.PHONY : SpectralResidualSaliencyExe/fast

IdentityClassifier.o: IdentityClassifier.cpp.o
.PHONY : IdentityClassifier.o

# target to build an object file
IdentityClassifier.cpp.o:
	$(MAKE) -f CMakeFiles/IdentityClassifier.dir/build.make CMakeFiles/IdentityClassifier.dir/IdentityClassifier.cpp.o
.PHONY : IdentityClassifier.cpp.o

IdentityClassifier.i: IdentityClassifier.cpp.i
.PHONY : IdentityClassifier.i

# target to preprocess a source file
IdentityClassifier.cpp.i:
	$(MAKE) -f CMakeFiles/IdentityClassifier.dir/build.make CMakeFiles/IdentityClassifier.dir/IdentityClassifier.cpp.i
.PHONY : IdentityClassifier.cpp.i

IdentityClassifier.s: IdentityClassifier.cpp.s
.PHONY : IdentityClassifier.s

# target to generate assembly for a file
IdentityClassifier.cpp.s:
	$(MAKE) -f CMakeFiles/IdentityClassifier.dir/build.make CMakeFiles/IdentityClassifier.dir/IdentityClassifier.cpp.s
.PHONY : IdentityClassifier.cpp.s

aci.o: aci.cpp.o
.PHONY : aci.o

# target to build an object file
aci.cpp.o:
	$(MAKE) -f CMakeFiles/ACI.dir/build.make CMakeFiles/ACI.dir/aci.cpp.o
.PHONY : aci.cpp.o

aci.i: aci.cpp.i
.PHONY : aci.i

# target to preprocess a source file
aci.cpp.i:
	$(MAKE) -f CMakeFiles/ACI.dir/build.make CMakeFiles/ACI.dir/aci.cpp.i
.PHONY : aci.cpp.i

aci.s: aci.cpp.s
.PHONY : aci.s

# target to generate assembly for a file
aci.cpp.s:
	$(MAKE) -f CMakeFiles/ACI.dir/build.make CMakeFiles/ACI.dir/aci.cpp.s
.PHONY : aci.cpp.s

saliency/SpectralResidualSaliency.o: saliency/SpectralResidualSaliency.cpp.o
.PHONY : saliency/SpectralResidualSaliency.o

# target to build an object file
saliency/SpectralResidualSaliency.cpp.o:
	$(MAKE) -f CMakeFiles/SpectralResidualSaliency.dir/build.make CMakeFiles/SpectralResidualSaliency.dir/saliency/SpectralResidualSaliency.cpp.o
.PHONY : saliency/SpectralResidualSaliency.cpp.o

saliency/SpectralResidualSaliency.i: saliency/SpectralResidualSaliency.cpp.i
.PHONY : saliency/SpectralResidualSaliency.i

# target to preprocess a source file
saliency/SpectralResidualSaliency.cpp.i:
	$(MAKE) -f CMakeFiles/SpectralResidualSaliency.dir/build.make CMakeFiles/SpectralResidualSaliency.dir/saliency/SpectralResidualSaliency.cpp.i
.PHONY : saliency/SpectralResidualSaliency.cpp.i

saliency/SpectralResidualSaliency.s: saliency/SpectralResidualSaliency.cpp.s
.PHONY : saliency/SpectralResidualSaliency.s

# target to generate assembly for a file
saliency/SpectralResidualSaliency.cpp.s:
	$(MAKE) -f CMakeFiles/SpectralResidualSaliency.dir/build.make CMakeFiles/SpectralResidualSaliency.dir/saliency/SpectralResidualSaliency.cpp.s
.PHONY : saliency/SpectralResidualSaliency.cpp.s

test/GrabcutTest.o: test/GrabcutTest.cpp.o
.PHONY : test/GrabcutTest.o

# target to build an object file
test/GrabcutTest.cpp.o:
	$(MAKE) -f CMakeFiles/GrabCutExe.dir/build.make CMakeFiles/GrabCutExe.dir/test/GrabcutTest.cpp.o
.PHONY : test/GrabcutTest.cpp.o

test/GrabcutTest.i: test/GrabcutTest.cpp.i
.PHONY : test/GrabcutTest.i

# target to preprocess a source file
test/GrabcutTest.cpp.i:
	$(MAKE) -f CMakeFiles/GrabCutExe.dir/build.make CMakeFiles/GrabCutExe.dir/test/GrabcutTest.cpp.i
.PHONY : test/GrabcutTest.cpp.i

test/GrabcutTest.s: test/GrabcutTest.cpp.s
.PHONY : test/GrabcutTest.s

# target to generate assembly for a file
test/GrabcutTest.cpp.s:
	$(MAKE) -f CMakeFiles/GrabCutExe.dir/build.make CMakeFiles/GrabCutExe.dir/test/GrabcutTest.cpp.s
.PHONY : test/GrabcutTest.cpp.s

test/saliency/SpectralResidualSaliencyTest.o: test/saliency/SpectralResidualSaliencyTest.cpp.o
.PHONY : test/saliency/SpectralResidualSaliencyTest.o

# target to build an object file
test/saliency/SpectralResidualSaliencyTest.cpp.o:
	$(MAKE) -f CMakeFiles/SpectralResidualSaliencyExe.dir/build.make CMakeFiles/SpectralResidualSaliencyExe.dir/test/saliency/SpectralResidualSaliencyTest.cpp.o
.PHONY : test/saliency/SpectralResidualSaliencyTest.cpp.o

test/saliency/SpectralResidualSaliencyTest.i: test/saliency/SpectralResidualSaliencyTest.cpp.i
.PHONY : test/saliency/SpectralResidualSaliencyTest.i

# target to preprocess a source file
test/saliency/SpectralResidualSaliencyTest.cpp.i:
	$(MAKE) -f CMakeFiles/SpectralResidualSaliencyExe.dir/build.make CMakeFiles/SpectralResidualSaliencyExe.dir/test/saliency/SpectralResidualSaliencyTest.cpp.i
.PHONY : test/saliency/SpectralResidualSaliencyTest.cpp.i

test/saliency/SpectralResidualSaliencyTest.s: test/saliency/SpectralResidualSaliencyTest.cpp.s
.PHONY : test/saliency/SpectralResidualSaliencyTest.s

# target to generate assembly for a file
test/saliency/SpectralResidualSaliencyTest.cpp.s:
	$(MAKE) -f CMakeFiles/SpectralResidualSaliencyExe.dir/build.make CMakeFiles/SpectralResidualSaliencyExe.dir/test/saliency/SpectralResidualSaliencyTest.cpp.s
.PHONY : test/saliency/SpectralResidualSaliencyTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ACI"
	@echo "... GrabCutExe"
	@echo "... IdentityClassifier"
	@echo "... SpectralResidualSaliency"
	@echo "... SpectralResidualSaliencyExe"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... IdentityClassifier.o"
	@echo "... IdentityClassifier.i"
	@echo "... IdentityClassifier.s"
	@echo "... aci.o"
	@echo "... aci.i"
	@echo "... aci.s"
	@echo "... saliency/SpectralResidualSaliency.o"
	@echo "... saliency/SpectralResidualSaliency.i"
	@echo "... saliency/SpectralResidualSaliency.s"
	@echo "... test/GrabcutTest.o"
	@echo "... test/GrabcutTest.i"
	@echo "... test/GrabcutTest.s"
	@echo "... test/saliency/SpectralResidualSaliencyTest.o"
	@echo "... test/saliency/SpectralResidualSaliencyTest.i"
	@echo "... test/saliency/SpectralResidualSaliencyTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

